export default {
    GET_INFORMATIONS: 'GET_INFORMATIONS',
    SET_USER: 'SET_USER',
    GET_USER: 'GET_USER',
    DELETE_USER: 'DELETE_USER',
    SET_IMAGE: 'SET_IMAGE',
    UPLOAD_TROPHY: 'UPLOAD_TROPHY',
    SAVE_URL_TROPHY: 'SAVE_URL_TROPHY',
    UPLOAD_IMAGE: 'UPLOAD_IMAGE',
    RENAME_IMAGE: 'RENAME_IMAGE',
    SET_USER_INFORMATIONS: 'SET_USER_INFORMATIONS',
    SET_STARS: 'SET_STARS',
    SEARCH: 'SEARCH',
};
